# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DIPS | Tech
email: post@dips.no
description: > # this means to ignore newlines until "baseurl:"
  Velkommen til DIPS ASAs tech-blogg! DIPS ASA er Norges største leverandør av e-helse systemer og vi er et av Norges største programvarehus.
  
  På bloggen vil flere av våre 120 dyktige utviklere gi oss innblikk i noen av de tekniske problemstillingene vi står ovenfor på veien mot å lage verdens beste e-helse system.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tech.dips.no" # the base hostname & protocol for your site
twitter_username: DIPSASA
github_username: DIPSASA
facebook_username: DIPS-ASA-100422586702214/?fref=ts
linkedin_username: company/dips-asa
karriere_url: https://www.dips.no/karriere

excerpt_separator: "<!--more-->"

# Build settings
markdown: kramdown

# Tagging
tag_page_layout: tag_page
tag_page_dir: tag
